# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d77660211172b72f8ff49fb2a2af1f44c0b754b3cdb5e9f987fb5a4772d458d60d1d4481396caec9e95adf52b568a97ec4c6ef592946f8a59c50dae49d7e547

test:
  secret_key_base: 97899d86f701d185d8184f6f6c13756a0aba16e4c741f7bdef3f67dc011371ab26920852a55e2ff45c8b3ca6f9dd3634af92708371ba8e796bfc9b6e1d758892

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
